MvcApiPersonajesAWS/Models/ErrorViewModel.cs
namespace MvcApiPersonajesAWS.Models {
    public class ErrorViewModel {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcApiPersonajesAWS/Models/Personaje.cs
namespace MvcApiPersonajesAWS.Models {
    public class Personaje {

        public int IdPersonaje { get; set; }
        public string Nombre { get; set; }
        public string Imagen { get; set; }

    }
}

MvcApiPersonajesAWS/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcApiPersonajesAWS.Models;
using System.Diagnostics;

namespace MvcApiPersonajesAWS.Controllers {
    public class HomeController : Controller {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger) {
            _logger = logger;
        }

        public IActionResult Index() {
            return View();
        }

        public IActionResult Privacy() {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error() {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcApiPersonajesAWS/Controllers/PersonajesController.cs
using Microsoft.AspNetCore.Mvc;
using MvcApiPersonajesAWS.Models;
using MvcApiPersonajesAWS.Services;

namespace MvcApiPersonajesAWS.Controllers {
    public class PersonajesController : Controller {

        private ServiceApiPersonajes service;

        public PersonajesController(ServiceApiPersonajes service) {
            this.service = service;
        }

        public IActionResult Listado() {
            return View();
        }
        
        public IActionResult Details(int idPersonaje) {
            return View(idPersonaje);
        }

        public async Task<IActionResult> ApiPersonajes() {
            List<Personaje> personajes = await this.service.GetPersonajesAsync();
            return View(personajes);
        }


        public IActionResult CreatePersonaje() {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreatePersonaje(Personaje personaje) {
            await this.service.InsertPersonajeAsync(personaje.Nombre, personaje.Imagen);
            return RedirectToAction("ApiPersonajes");
        }


        public IActionResult UpdatePersonaje() {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> UpdatePersonaje(Personaje personaje) {
            await this.service.UpdatePersonajeAsync(personaje.IdPersonaje, personaje.Nombre, personaje.Imagen);
            return RedirectToAction("ApiPersonajes");
        }


        public async Task<IActionResult> DeletePersonaje(int idPersonaje) {
            await this.service.DeletePersonajeAsync(idPersonaje);
            return RedirectToAction("ApiPersonajes");
        }


        public async Task<IActionResult> Test() {
            ViewData["TEST"] = await this.service.TestApiAsync();
            return View();
        }

    }
}

MvcApiPersonajesAWS/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcApiPersonajesAWS/Views/Personajes/ApiPersonajes.cshtml
@model IEnumerable<MvcApiPersonajesAWS.Models.Personaje>

@{
    ViewData["Title"] = "ApiPersonajes";
}

<h1>ApiPersonajes</h1>

<p>
    <a asp-action="CreatePersonaje">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdPersonaje)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imagen)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdPersonaje)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Imagen)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                <a asp-controller="Personajes" asp-action="UpdatePersonaje">Update</a>
                <a asp-controller="Personajes" asp-action="DeletePersonaje" asp-route-idPersonaje="@item.IdPersonaje">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

MvcApiPersonajesAWS/Views/Personajes/CreatePersonaje.cshtml
@model MvcApiPersonajesAWS.Models.Personaje

@{
    ViewData["Title"] = "CreatePersonaje";
}

<h1>CreatePersonaje</h1>

<h4>Personaje</h4>
<hr />
<div class="row">
    <div class="col-md-4">
    <form asp-action="CreatePersonaje" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Nombre" class="control-label"></label>
            <input asp-for="Nombre" class="form-control" />
            <span asp-validation-for="Nombre" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Imagen" class="control-label"></label>
            <input asp-for="Imagen" class="form-control" />
            <span asp-validation-for="Imagen" class="text-danger"></span>
        </div>
        <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
        </div>
    </form>
    </div>
</div>



<div>
<a asp-action="ApiPersonajes">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

MvcApiPersonajesAWS/Views/Personajes/Details.cshtml
@model int

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Personaje</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            IdPersonaje
        </dt>
        <dd class="col-sm-10" id="idPersonaje"></dd>
        <dt class="col-sm-2">
            Nombre
        </dt>
        <dd class="col-sm-10" id="nombre"></dd>
        <dt class="col-sm-2">
            Imagen
        </dt>
        <dd class="col-sm-10">
            <img id="imagen" src="" style="width: 150px;" alt="Personaje Image" />
        </dd>
    </dl>
</div>

<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model }) |
    <a asp-action="Listado">Back to List</a>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            console.log("david");
            $.get("https://3.95.66.174/api/Personajes/GetPersonaje/" + @Model, function (data) {
                console.log("david1");
                $("#idPersonaje").text(data.idPersonaje);
                $("#nombre").text(data.nombre);
                $("#imagen").attr("src", data.imagen);
            });
        });
    </script>
}

MvcApiPersonajesAWS/Views/Personajes/Listado.cshtml
@{
    ViewData["Title"] = "Listado de personajes";
}

<h1 style="color: red; margin: auto;">
    Personajes
</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<div id="content"></div>

@section Scripts {
    <script>
        $(document).ready(function (){
            $.get("https://3.85.203.186/api/Personajes/GetPersonajes", function (data) {
                // Limpiar el contenido de la tabla antes de agregar los datos
                $("#content").empty();

                // Crear la estructura de la tabla
                var table = $("<table>").addClass("personajes-table table table-dark");
                var thead = $("<thead>").appendTo(table);
                var tbody = $("<tbody>").appendTo(table);

                // Crear la fila de encabezado
                var headerRow = $("<tr>").appendTo(thead);
                $("<th>").text("ID").appendTo(headerRow);
                $("<th>").text("Nombre").appendTo(headerRow);
                $("<th>").text("Imagen").appendTo(headerRow);
                $("<th>").text("Acciones").appendTo(headerRow);

                // Iterar sobre los datos y agregar filas a la tabla
                data.forEach(function (personaje) {
                    var row = $("<tr>").appendTo(tbody);
                    $("<td>").text(personaje.idPersonaje).appendTo(row);
                    $("<td>").text(personaje.nombre).appendTo(row);
                    $("<td>").html('<img src="' + personaje.imagen + '" style="width: 150px;">').appendTo(row);
                    $("<td>").html('<a href="/Personajes/Details?idPersonaje=' + personaje.idPersonaje  + '" class="btn btn-primary">Detalles</a>').appendTo(row);
                });

                // Agregar la tabla al elemento con el ID "content"
                $("#content").append(table);
            });
        });
    </script>
}

MvcApiPersonajesAWS/Views/Personajes/Test.cshtml
<h1 style="color: red;">@ViewData["TEST"]</h1>

MvcApiPersonajesAWS/Views/Personajes/UpdatePersonaje.cshtml
@model MvcApiPersonajesAWS.Models.Personaje

@{
    ViewData["Title"] = "UpdatePersonaje";
}

<h1>UpdatePersonaje</h1>

<h4>Personaje</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="UpdatePersonaje">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdPersonaje" class="control-label"></label>
                <input asp-for="IdPersonaje" class="form-control" />
                <span asp-validation-for="IdPersonaje" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagen" class="control-label"></label>
                <input asp-for="Imagen" class="form-control" />
                <span asp-validation-for="Imagen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="ApiPersonajes">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcApiPersonajesAWS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcApiPersonajesAWS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcApiPersonajesAWS.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcApiPersonajesAWS</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Personajes" asp-action="Listado">GetPersonajes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Personajes" asp-action="ApiPersonajes">ApiPersonajes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Personajes" asp-action="Test">Test</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Personajes" asp-action="UpdatePersonaje">Update</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MvcApiPersonajesAWS - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>